import { createApp } from "vue";
import "mdb-vue-ui-kit/css/mdb.min.css";
const pinia = createPinia();
import App from "./App.vue";
import { createPinia } from "pinia";
import { router } from "./router";
const app = createApp(App);
app.use(router);
app.use(pinia);
app.mount("#app");
